config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'

  get 'orders/update'
  post 'orders/update'
  get 'orders/create'

  get 'orders/index'

  get 'orders/show'

  resources :products, only: [:index,:destroy,:new,:create]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :widgets
  resources :widgets
  resources :articles
  resources :orders
  mount Ckeditor::Engine => '/ckeditor'

  
  root 'home#home'
  get 'unauthorizePage', to: 'home#unauthorized'
  get 'video', to: 'gallery#video'
  get 'picture', to: 'gallery#picture'
  get 'about', to: 'about#about'
  get 'store', to: 'products#index'
  get 'display', to: 'articles#display'
  
  resources :users, except: [:new]
  get 'signup' , to: 'users#new'
  get 'done', to: 'users#done'
  get 'item', to: 'products#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :applies
   resources :applyas
  get 'checkProgress', to: 'users#checkProgress'
  get 'switchStatus', to: 'users#flipStatus'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order("created_at DESC")
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def display
    @articles = Article.order("created_at DESC")
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, notice: "The article has been successfully created."
    else
      render action: "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to articles_path, notice: "The article has been successfully updated."
    else
      render action: "edit"
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "Article was successfully deleted"
    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container col-sm-offset-1 col-sm-10">
<% if @article.errors.any? %>
  <ul>
    <%= @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @article do |f| %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
  </div>
  <div>
    <%= f.cktext_area :body, rows: 10 %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/articles/display.html.erb
<div align="center">
  </div>
  <% @articles.each do |article| %>
  <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
  <div class="well well-lg">
  <div class="article-title">
  <h2 align="center"><%= article.title %></h2>
  </div>
  <div class="article-body">
  <%= article.body.html_safe %>
  </div>
  </div>
  </div>
  </div>
  <% end %>

app/views/articles/edit.html.erb
<% if current_user_manage? %>
  <div class="container col-sm-offset-1 col-sm-10">
    <h3>
      <%= "Editing #{@article.title}"%>
    </h3>
  </div>
  <%= render "form" %>
<% else %>
  <h1 align="center">Sorry, You are not authorized! </h1>
<% end %>

app/views/articles/index.html.erb
<% if current_user_manage? %>
  <h1 align="center">Listing all articles</h1>
  <div align="center">
  <%= link_to "New article", new_article_path, class: "btn btn-xs btn-primary" %>
  </div>
  <% @articles.each do |article| %>
  <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
  <div class="well well-lg">
  <div class="article-title">
  <%= link_to article.title, article_path(article) %>
  </div>
  <div class="article-body">
  <%= truncate(article.body.html_safe, length: 100) %>
  </div>
  <div class="article-actions">
  <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
  <%= link_to "Delete this article", article_path(article), method: :delete,
  data: { confirm: "Are you sure you want to delete the article?"},
  class: "btn btn-xs btn-danger" %>
  </div>
  </div>
  </div>
  </div>
  <% end %>
<% else %>
  <h1 align="center">Sorry, You are not authorized! </h1>
<% end %>

app/views/articles/new.html.erb
<% if current_user_manage? %>
  <h3 align = "center"> New Article</h3>
  <%= render "form" %>
<% else %>
  <h1 align="center">Sorry, You are not authorized! </h1>
<% end %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
<h4 class="center description"><strong>Content:</strong></h4>
<hr>
<%= simple_format(@article.body.html_safe) %>
<div class="article-actions">
<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
<%= link_to "Delete this article", article_path(@article), method: :delete,
data: { confirm: "Are you sure you want to delete the article?"},
class: "btn btn-xs btn-danger" %>
<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
</div>
</div>