config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'

  get 'orders/update'
  post 'orders/update'
  get 'orders/create'

  get 'orders/index'

  get 'orders/show'

  resources :products, only: [:index,:destroy,:new,:create]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :widgets
  resources :widgets
  resources :articles
  resources :orders
  mount Ckeditor::Engine => '/ckeditor'

  
  root 'home#home'
  get 'unauthorizePage', to: 'home#unauthorized'
  get 'video', to: 'gallery#video'
  get 'picture', to: 'gallery#picture'
  get 'about', to: 'about#about'
  get 'store', to: 'products#index'
  get 'display', to: 'articles#display'
  
  resources :users, except: [:new]
  get 'signup' , to: 'users#new'
  get 'done', to: 'users#done'
  get 'item', to: 'products#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :applies
   resources :applyas
  get 'checkProgress', to: 'users#checkProgress'
  get 'switchStatus', to: 'users#flipStatus'

end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_secure_password
    has_one :apply
    before_save { self.email = email.downcase }
    
    validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
    uniqueness:  { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
    validates :password, :presence =>true, :confirmation =>true
    validates_confirmation_of :password
    
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :logged_in_user, only: [:index,:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def new
    @user = User.new
  end
  
  def destroy
    @user = User.find(params[:id])
    if !@user.apply0.nil?
      Apply.find(@user.apply0).destroy
    end
    if !@user.apply1.nil?
      Applya.find(@user.apply1).destroy
    end
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def flipStatus
    if current_user.username == 'root' && current_user.email == 'root'
      @toChange = !User.find(params[:id]).manageFlag
      User.find(params[:id]).update_attribute(:manageFlag,@toChange)
    end
    redirect_to users_path
  end
  
  def index
    if params[:commit]=="Refresh"
      session[:datefilter] = params[:datefilter]
      session[:userSearch] = params[:userSearch]
    end
    @datefilter = session[:datefilter]
    @userSearch = session[:userSearch]
    timeI = getTime(@datefilter)
    @users=User.all
    
    if current_user.username != 'root' || current_user.email != 'root'
      @users = @users.where({manageFlag: [false,nil]})
    else
      @users = @users.where.not("username like ? and email like ?",
                            "root","root")
    end
    
    if (@userSearch != nil?) && (@users != nil?)
      @users = @users.where("username like ? OR email like ?",
                            "%#{@userSearch}%","%#{@userSearch}%")
    end
    if !timeI==nil?
      @users = @users.find_all{|users| users.created_at.to_i<=timeI[1]&&users.created_at.to_i>=timeI[0]}
    end
    
    if params[:commit]=="CheckAll"
      @checkbox  = Array.new
      @users.each do |user|
        @checkbox << user.id.to_s
      end
    else
      @checkbox = params[:checkbox]
    end
    
    if params[:commit]=="delete"
      @checkbox.each do |user_id_str|
        @userToD = User.find(user_id_str.to_i)
        if !@userToD.manageFlag?
          if !@userToD.apply0.nil?
            Apply.find(@userToD.apply0).destroy
          end
          if !@userToD.apply1.nil?
            Applya.find(@userToD.apply1).destroy
          end
          @userToD.destroy
          @users.delete(@userToD)
        end
      end
      flash[:success] = "Users have been deleted"
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "#{@user.username} was successfully created."
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def show
    id = params[:id]
    @user = User.find(id) # look up movie by unique ID
    if !current_user?(@user)
      render 'home/unauthorized'
      return
    end
    if !@user.apply0.nil?
      @apply0 = Apply.find(@user.apply0)
    end
    if !@user.apply1.nil?
      @apply1 = Applya.find(@user.apply1)
    end
    # if !@user.apply2.nil?
    #   @apply2 = Apply.find(@user.apply2)
    # end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end
  
  def checkProgress
    @user = User.find(params[:id])
    if !current_user?(@user)
      render 'home/unauthorized'
      return
    end
  end
  
  private
    def user_params
    params.require(:user).permit(:username, :email, :password)
    end
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
        # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user_manage?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def getTime(datefilter)
    #datefilter=11%2F20%2F2017+-+11%2F29%2F2017
    timeStr=/(\d+)\/(\d+)\/(\d+) \- (\d+)\/(\d+)\/(\d+)/.match(datefilter)
    if !timeStr==nil?
      timeI = Array.new
      timeI << Date.new(timeStr[3].to_i,timeStr[1].to_i,timeStr[2].to_i).to_time.to_i + 21600
      timeI << Date.new(timeStr[6].to_i,timeStr[4].to_i,timeStr[5].to_i).to_time.to_i + 21600 + 86400
      return timeI
    else
      return nil
    end
  end
end

app/views/users/_form.html.erb
<div class='row'>
<div class='col-xs-12'>
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :username %>
</div>
<div class="col-sm-8">
<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
</div>
</div>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :email %>
</div>
<div class="col-sm-8">
<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
</div>
</div>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :password %>
</div>
<div class="col-sm-8">
<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
</div>
</div>
<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: 'btn btn-primary btn-lg') %>
</div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-2">
 [<%= link_to "cancel", root_path %>] 
</div>
</div>
</div>

app/views/users/_progressShow.html.erb
<%= form_for(apply) do |form| %>
  <form>
    <div class="container col-sm-offset-1">
      <div class="form-group row">
        <div class="col-sm-2">
          <%= form.select :admission, [['Please Choose..',nil],['Admit',true], ['Reject',false]],{}, disabled: true,class: "form-control"%> admit or not?
        </div>
        <div class="col-sm-8">
          <%= form.text_area :comment, class: "form-control", placeholder: "Comments for this applicant", type: "text", rows:"8", disabled: true %>
        </div>
      </div>
    </div>
  </form>
<% end %>

app/views/users/checkProgress.html.erb
<% if current_user?(@user) %>
  <h1 align="center">Application Process</h1>
    <% if (@user.apply0.nil?)&&(@user.apply1.nil?)&&(@user.apply2.nil?) %>
      <h1 align="center">Please create your application form first </h1>
    <% else %>
      <% if !@user.apply0.nil? %>
        <% if !Apply.find(@user.apply0).admission.nil? %>
          <h2 align="center">Application form for Seniors status </h2>
          <%= render 'progressShow', apply: Apply.find(@user.apply0)%>
        <% else%>
          <h2 align="center">Your application form for Seniors is still in processing </h2>
        <% end %>
      <% end %>
      
      <% if !@user.apply1.nil? %>
        <% if !Applya.find(@user.apply1).admission.nil? %>
          <h2 align="center">Application form for Juniors status </h2>
          <%= render 'progressShow', apply: Applya.find(@user.apply1)%>
        <% else%>
          <h2 align="center">Your application form for Juniors is still in processing </h2>
        <% end %>
      <% end %>
      
      <% if !@user.apply2.nil? %>
        <% if !Apply.find(@user.apply2).admission.nil? %>
          <h2 align="center">Application form 3 status </h2>
          <%= render 'progressShow', apply: Apply.find(@user.apply2)%>
        <% else%>
          <h2 align="center">Your application form 3 is still in processing </h2>
        <% end %>
      <% end %>
    <% end %>
<% else %>
  <h1 align="center">Sorry, You can only view your information </h1>
<% end %>

app/views/users/edit.html.erb
<h1 align="center">Update your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Listing all users</h1>
<form method="get" action=users>
  <div class="form-group row">
    <div class="col-xs-8 col-xs-offset-2">
      <label for="userSearch" class="col-xs-2">Search</label>
      <div class="col-xs-10">
        <%= text_field_tag :userSearch, @userSearch, class: "form-control",placeholder: "Search by name or Email",value: @userSearch%>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-xs-offset-2 col-xs-8">
      <label for="timeIntervalChoose" class="col-xs-4">Please specify time interval</label>
      <div class="col-xs-8">
        <%= text_field_tag :datefilter, @datefilter,name: "datefilter", class: "form-control",value: @datefilter%>
        <script type="text/javascript">
          $(function() {
            $('input[name="datefilter"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: 'Clear'
                }
            });
            $('input[name="datefilter"]').on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
            });
            $('input[name="datefilter"]').on('cancel.daterangepicker', function(ev, picker) {
                $(this).val('');
            });
          });
        </script>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-xs-2 col-xs-offset-9">
      <button type="submit" name="commit" value="Refresh" class="btn btn-primary">Submit</button>
    </div>
  </div>
</form>
<form>
  <% @users.each do |user| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= check_box_tag 'checkbox[]', user.id, (@checkbox || {}).include?(user.id.to_s) %>
            <%= user.username %>
            <% if current_user.username == 'root' && current_user.email == 'root' %>
              <% if user.manageFlag == true %>
                <%=link_to "Switch to normal user", switchStatus_path(:id => user.id) %>
              <% else %>
                <%=link_to "Switch to manager", switchStatus_path(:id => user.id)  %>
              <% end %>
            <%end%>
          </div>
            <div class="article-body">
              <%= user.email %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="form-group row">
    <div class="col-xs-1 col-xs-offset-8">
      <% if params[:commit]!="CheckAll"%>
        <%= link_to "Check All", users_path(:commit => "CheckAll"), class: "btn btn-success" %>
      <% else %>
        <%= link_to "Clear All", users_path(:commit => "UncheckAll"), class: "btn btn-success" %>
      <% end %>
    </div>
    <div class="col-xs-offset-1">
      <button type="submit" name="commit" value="delete" 
      onclick="return confirm('Are you sure to delete these users?(Only normal users will be deleted)')" class="btn btn-danger">Delete</button>
    </div>
  </div>
</form>

app/views/users/new.html.erb
<h1 align="center">TAMU Racing Registration</h1>
<div class='row'>
<div class='col-xs-12'>
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :username %>
</div>
<div class="col-sm-8">
<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
</div>
</div>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :email %>
</div>
<div class="col-sm-8">
<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
</div>
</div>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :password %>
</div>
<div class="col-sm-8">
<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
</div>
</div>

<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: 'btn btn-primary btn-lg') %>
</div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-2">
 [<%= link_to "cancel", root_path %>] 
</div>
</div>
</div>

app/views/users/show.html.erb
<h2 align="center">Username: <%= @user.username %></h2>

<div class="well col-xs-8 col-xs-offset-2">

<h4 class="center description"><strong>Email:</strong> <%= simple_format(@user.email) %> </h4>

<hr>


<div class="article-actions">
<% if !(@user.manageFlag == true) %>
  <% if @apply0.nil? %>
    <%= link_to "Create application form for Seniors", new_apply_path(:user_id => @user.id), class: "btn btn-xs btn-primary" %>
  <% else %>
    <%= link_to "Edit application form for Seniors", edit_apply_path(@apply0), class: "btn btn-xs btn-primary" %>
    <% if @apply0.admission.nil?%>
      <%= link_to "Delete application form for Seniors", apply_path(@apply0), method: :delete,
      data: { confirm: "Are you sure you want to delete the form?"},class: "btn btn-xs btn-danger" %>
    <% end %>
  <% end %>
  <% if @apply1.nil? %>
    <%= link_to "Create application form for Juniors", new_applya_path(:user_id => @user.id), class: "btn btn-xs btn-primary" %>
  <% else %>
    <%= link_to "Edit application form for Juniors", edit_applya_path(@apply1), class: "btn btn-xs btn-primary" %>
    <% if @apply1.admission.nil?%>
      <%= link_to "Delete application form for Juniors", applya_path(@apply1), method: :delete,
      data: { confirm: "Are you sure you want to delete the form?"},class: "btn btn-xs btn-danger" %>
    <% end %>
  <% end %>
  <% if (!@apply0.nil?)||(!@apply1.nil?)||(!@apply2.nil?) %>
    <%= link_to "View Application Process", checkProgress_path(:id => current_user.id) , class: "btn btn-xs btn-success" %>
  <% end %>
<% else %>
  <%= link_to "Edit news", articles_path, class: "btn btn-xs btn-primary" %>
  <%= link_to "Manage applicants", applies_path, class: "btn btn-xs btn-success" %>
  <%= link_to "Manage Users", users_path, class: "btn btn-xs btn-danger" %>
  <%= link_to "Manage Orders", orders_path, class: "btn btn-xs btn-danger" %>
<% end %>
</div>

</div>