config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'

  get 'orders/update'
  post 'orders/update'
  get 'orders/create'

  get 'orders/index'

  get 'orders/show'

  resources :products, only: [:index,:destroy,:new,:create]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :widgets
  resources :widgets
  resources :articles
  resources :orders
  mount Ckeditor::Engine => '/ckeditor'

  
  root 'home#home'
  get 'unauthorizePage', to: 'home#unauthorized'
  get 'video', to: 'gallery#video'
  get 'picture', to: 'gallery#picture'
  get 'about', to: 'about#about'
  get 'store', to: 'products#index'
  get 'display', to: 'articles#display'
  
  resources :users, except: [:new]
  get 'signup' , to: 'users#new'
  get 'done', to: 'users#done'
  get 'item', to: 'products#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :applies
   resources :applyas
  get 'checkProgress', to: 'users#checkProgress'
  get 'switchStatus', to: 'users#flipStatus'

end

app/models/apply.rb
class Apply < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true,
  uniqueness: { case_sensitive: false }
  

end

app/models/applya.rb
class Applya < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private

  def update_subtotal
    self[:subtotal] = subtotal
    self[:shipping] = 10
    self[:tax] = subtotal * 0.0825
    self[:total] = subtotal + self[:shipping] + self[:tax]
  end
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  #validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
  
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, :presence => true,
  :content_type => { :content_type => "image/png" },
  :size => { :in => 0..5.megabytes }
  default_scope { where(active: true) }
  
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_secure_password
    has_one :apply
    before_save { self.email = email.downcase }
    
    validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
    uniqueness:  { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
    validates :password, :presence =>true, :confirmation =>true
    validates_confirmation_of :password
    
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home

  end
  def unauthorized
    
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/helpers/applyas_helper.rb
module ApplyasHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
    # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def current_user_manage?
    @current_user ||= User.find_by(id: session[:user_id])
    if @current_user.nil?
      false
    else
      @current_user.manageFlag == true
    end
  end
   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
    # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
    # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def getTime(datefilter)
    #datefilter=11%2F20%2F2017+-+11%2F29%2F2017
    timeStr=/(\d+)\/(\d+)\/(\d+) \- (\d+)\/(\d+)\/(\d+)/.match(datefilter)
    if !timeStr==nil?
      timeI = Array.new
      timeI << Date.new(timeStr[3].to_i,timeStr[1].to_i,timeStr[2].to_i).to_time.to_i + 21600
      timeI << Date.new(timeStr[6].to_i,timeStr[4].to_i,timeStr[5].to_i).to_time.to_i + 21600 + 86400
      return timeI
    else
      return nil
    end
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", new_order_path, class: "btn btn-link" %>

app/views/layouts/_message.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>'>

<a href="#" class="close" data-dismiss="alert">×</a>

<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

</div>

<% end %>

</div>

</div>

app/views/layouts/_navigation.html.erb
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
 
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Texas A&M SAE", root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav myclass">
      <li><%= link_to "News", display_path%></li>
      <li><%= link_to "Online Store", store_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gallery <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Picture Gallery", picture_path%></li>
            <li><%= link_to "Video Gallery", video_path%></li>
          </ul>
        </li>
      </ul>

<ul class="nav navbar-nav navbar-right">     
        <% if logged_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Change password", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
         
        <li><%= link_to "About", about_path %></li>

        <li class="cart-text"><%= render 'layouts/cart_text' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TamuRacing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation'%>
  <%= render 'layouts/message'%>
  <%= yield %>
    
</body>
</html>